version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/app/html
    ports:
      - "8080:8080"
    environment:
      - HTML_DIR=/app/html
      - START_URL=en.wikipedia.org/wiki/United_Kingdom
      - MAX_CONCURRENT_REQUESTS=5
      - ALLOWED_HREF_REGEX=en.wikipedia.org/wiki
